### ISSUE TITLE
Explain what is XOR gate

### ISSUE THREAD

**Issue by Vinetos** [Vinetos/neural-network-xor#4]
Update the README and explain what is the XOR gate with a table with Input / Output
 instead of Image

**Comment by NirmalSilwal** [comment]
can I work on this?

**Comment by Vinetos** [comment]
Just DO IT :smiley:

**Comment by NirmalSilwal** [comment]
yay! let me contribute!

**Comment by NirmalSilwal** [comment]
seems XOR explanation has been added, can I enhance it further?

**Comment by Vinetos** [comment]
Yup, go for it 👍👌
